<!--NAVIGATION-->

<a href="https://colab.research.google.com/github/bpesquet/machine-learning-katas/blob/master/data/Tensor_Management.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open in Google Colaboratory"></a>


# Kata: Tensor Management

## Instructions

This is a self-correcting exercise generated by [nbgrader](https://github.com/jupyter/nbgrader). 

Complete the cells beginning with `# YOUR CODE HERE` and run the subsequent cells to check your code.

## Part 1: Tensor Basics

In [1]:
# Import NumPy
import numpy as np
import torch


### Question

Create a 2D tensor (a matrix) with dimensions (3,4) containing integer values of your choice. Store this tensor in a variable named `x`.

In [2]:
# YOUR CODE HERE
x=np.random.randint(10, size=(3, 4))
x = torch.from_numpy(x)
print(x)
print(x.ndim)
print(x.shape)

tensor([[1, 6, 1, 6],
        [5, 9, 9, 0],
        [4, 7, 3, 8]], dtype=torch.int32)
2
torch.Size([3, 4])


In [3]:
print(x)
# Assert dimensions
assert x.ndim == 2
assert x.shape == (3, 4)
# Assert data type 
assert issubclass(x.dtype.type, np.integer)

tensor([[1, 6, 1, 6],
        [5, 9, 9, 0],
        [4, 7, 3, 8]], dtype=torch.int32)


AttributeError: 'torch.dtype' object has no attribute 'type'

### Question

Update the shape of the previous tensor so that it has dimensions (6,2).

In [4]:
# YOUR CODE HERE
x= x.reshape(6,2)
print(x.ndim)
print(x.shape)

2
torch.Size([6, 2])


In [5]:
print(x)
# Assert tensor dimensions
assert x.ndim == 2
assert x.shape == (6, 2)

tensor([[1, 6],
        [1, 6],
        [5, 9],
        [9, 0],
        [4, 7],
        [3, 8]], dtype=torch.int32)


### Question

Change the type of the previous tensor values to `float32`.

In [6]:
# YOUR CODE HERE
x= x.float()
#x = x.astype('float32')


In [7]:
print(x)
# Assert data type
assert issubclass(x.dtype.type, np.floating)

tensor([[1., 6.],
        [1., 6.],
        [5., 9.],
        [9., 0.],
        [4., 7.],
        [3., 8.]])


AttributeError: 'torch.dtype' object has no attribute 'type'

### Question

Normalize the previous tensor so that it has a mean of 0 and a standard deviation of 1 on its first axis.

In [8]:
# YOUR CODE HERE
x = (x - x.mean(axis=0)) / x.std(axis=0)

In [9]:
print(x)
x_mean = x.mean(axis=0)
x_std = x.std(axis=0)
# Assert mean
assert np.abs(np.max(x_mean)) < 10**-6
# Assert standard deviation
assert np.abs(np.max(x_std-1)) < 10**-6

tensor([[-0.9462,  0.0000],
        [-0.9462,  0.0000],
        [ 0.3896,  0.9487],
        [ 1.7254, -1.8974],
        [ 0.0557,  0.3162],
        [-0.2783,  0.6325]])


TypeError: max() received an invalid combination of arguments - got (axis=NoneType, out=NoneType, ), but expected one of:
 * ()
 * (Tensor other)
 * (int dim, bool keepdim)
      didn't match because some of the keywords were incorrect: axis, out
 * (name dim, bool keepdim)
      didn't match because some of the keywords were incorrect: axis, out


## Part 2: One-hot Encoding

In [10]:
#from keras.utils import to_categorical


# virginica close to versicolor BAD
#0 - setosa
#1 - versicolor
#2 - virginica 

# Same distance between all the classes GOOD
#[1,0,0] - setosa
#[0,1,0] - versicolor
#[0,0,1] - virginica 


def to_categorical(y):
    """ 1-hot encodes a tensor """
    num_classes = np.max(y) + 1
    matrix = np.zeros([num_classes, len(y)], dtype='uint8')
    for i, x in enumerate(y):
        matrix[:, i] = np.eye(num_classes, dtype='uint8')[x]
    return matrix

tensor = to_categorical([3, 1, 0, 2, 1])
print(tensor)


[[0 0 1 0 0]
 [0 1 0 0 1]
 [0 0 0 1 0]
 [1 0 0 0 0]]


### Question

Encode the previous tensor into the `x` variable, following a binary representation (`one-hot encoding`).

In [ ]:
# YOUR CODE HERE
def to_categorical(y):
    """ 1-hot encodes a tensor """
    num_classes = np.max(y) + 2
    matrix = np.zeros([num_classes, len(y)], dtype='uint8')
    for i, x in enumerate(y):
        matrix[:, i] = np.eye(num_classes, dtype='uint8')[x]
    return matrix

tensor = to_categorical([3, 1, 0, 2, 1])
print(tensor)

In [ ]:
print(x)
# Assert one-hot encoding
assert x.shape == (5, 4)
assert np.array_equal([0,0,0,1], x[0])
assert np.array_equal([0,1,0,0], x[1])
assert np.array_equal([1,0,0,0], x[2])
assert np.array_equal([0,0,1,0], x[3])
assert np.array_equal([0,1,0,0], x[4])

## Part 3: Image Management

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
from sklearn.datasets import load_sample_images
# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [ ]:
# Load samples images
images = np.asarray(load_sample_images().images)
print(f'Number of images: {len(images)}. Images tensor: {images.shape}')

first_image = images[0]
# Display first image
plt.imshow(first_image)

# Print details about first image
print(f'First image: {first_image.shape}')

### Question

Store in variables respectively named `rgb_values_topleft` and `rgb_values_bottomright` the RGB values of the top-left and bottom-right pixels of the first image.

In [ ]:
# YOUR CODE HERE

In [ ]:
print(f'Top-left pixel: {rgb_values_topleft}')
assert rgb_values_topleft.shape == (3,)
print(f'Bottom-right pixel: {rgb_values_bottomright}')
assert rgb_values_bottomright.shape == (3,)

### Question

Reshape the previous `images` tensor into a 2D tensor.

In [ ]:
# YOUR CODE HERE

In [ ]:
# Assert new tensor dimensions
assert images.shape == (2, 819840)
# Assert RGB values of top-left in first image
assert np.array_equal(rgb_values_topleft, images[0,:3])
# Assert RGB values of bottom-right pixel in first image
assert np.array_equal(rgb_values_bottomright, images[0,819837:])