## Remember that the solutions need to be saved int variable provided.

In [1]:

import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [3]:
x = np.random.rand(10,10)
x

array([[0.77210986, 0.70745503, 0.9268876 , 0.52660899, 0.47831863,
        0.55015641, 0.41963749, 0.75421367, 0.81687295, 0.93465874],
       [0.15541472, 0.8358129 , 0.13831531, 0.03814523, 0.32104142,
        0.01235466, 0.5922111 , 0.7657744 , 0.79023946, 0.93131665],
       [0.39508766, 0.80081728, 0.10688108, 0.3438761 , 0.52189581,
        0.16893036, 0.03648146, 0.3460506 , 0.56865346, 0.88111999],
       [0.3925378 , 0.85586804, 0.30257109, 0.92731842, 0.83560596,
        0.79377946, 0.83323247, 0.86767019, 0.17576177, 0.03737998],
       [0.96253325, 0.80605597, 0.20823633, 0.84880809, 0.77102035,
        0.24394672, 0.47063199, 0.12129905, 0.3637632 , 0.45024795],
       [0.12756728, 0.74145346, 0.74021801, 0.28895856, 0.78647628,
        0.87964054, 0.97810164, 0.32704439, 0.35132881, 0.95547983],
       [0.43660242, 0.80046318, 0.02321351, 0.74862939, 0.82722364,
        0.54975181, 0.12388535, 0.05650822, 0.68373521, 0.41431166],
       [0.58628397, 0.7105613 , 0.2360493

In [4]:
x.min()

0.012354662927219318

In [5]:
x.max()

0.9781016362633924

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [6]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0

In [7]:
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**34. How to get all the dates corresponding to the month of July 2016**

In [9]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[W]')
print(x)

['2016-06-30' '2016-07-07' '2016-07-14' '2016-07-21']


**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [9]:
#2 points
sol41 = 0
sol42 = 0
comparisson = 0
# YOUR CODE HERE
#2 points
sol41 = np.random.uniform(size=(10,10))
sol42 = np.random.uniform(size=(10,10))
comparisson = sol41 == sol42
print(comparisson)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [10]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [11]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])

# YOUR CODE HERE
print(sol5)
sol5[[0,1]] = sol5[[1,0]]
print(sol5)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [1 2 3]]


In [12]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sol6 = 0
# YOUR CODE HERE
total_elements = len(arr)
cum_sum = np.cumsum(arr)
sol6 = cum_sum/total_elements
print(np.cumsum(arr))
print(sol6[-1])
print(sol6[0])
print(sol6[4])

[ 1  3  6 10 15 21 28 36 45 55]
5.5
0.1
1.5


In [ ]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5