## Remember that the solutions need to be saved int variable provided.

In [2]:

import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [3]:
x = np.random.rand(10,10)
x

array([[0.43703607, 0.99928486, 0.41034619, 0.89000722, 0.5951356 ,
        0.34544978, 0.52033996, 0.78814098, 0.03215524, 0.99850614],
       [0.36302256, 0.09574345, 0.61756841, 0.825613  , 0.82479947,
        0.09016245, 0.3437581 , 0.8260464 , 0.90411777, 0.64828961],
       [0.20445145, 0.20756379, 0.06951996, 0.50973671, 0.40010412,
        0.67014891, 0.25328562, 0.00916715, 0.88349886, 0.38580309],
       [0.99562923, 0.85597087, 0.03777197, 0.14200058, 0.1320561 ,
        0.55341716, 0.58397957, 0.98987299, 0.98682148, 0.26627361],
       [0.19891155, 0.92263131, 0.07332821, 0.51835583, 0.50935169,
        0.55527698, 0.29816602, 0.18717984, 0.40104316, 0.55515521],
       [0.59573302, 0.35641091, 0.57672936, 0.88270689, 0.88743818,
        0.62744573, 0.36114759, 0.23618182, 0.10016068, 0.094975  ],
       [0.87787633, 0.27576143, 0.36209291, 0.41856293, 0.11293487,
        0.58059969, 0.86122521, 0.14394764, 0.63453727, 0.05639651],
       [0.94109383, 0.65941424, 0.3915068

In [4]:
x.min()

0.00916714934128049

In [5]:
x.max()

0.999284856443319

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [6]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0

In [7]:
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**34. How to get all the dates corresponding to the month of July 2016**

In [8]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [14]:
#2 points
sol41 = 0
sol42 = 0
comparisson = 0
# YOUR CODE HERE
#2 points
sol41 = np.random.uniform(size=(10,10))
sol42 = np.random.uniform(size=(10,10))
comparisson = sol41 == sol42
print(comparisson)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [10]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [ ]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])

# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sol6 = 0
# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5