## Remember that the solutions need to be saved int variable provided.

In [1]:

import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [15]:
x = np.random.rand(10,10)
x

array([[0.30591174, 0.67407927, 0.23362198, 0.32799195, 0.82282973,
        0.58425214, 0.90411234, 0.1975327 , 0.40820347, 0.16599072],
       [0.94936985, 0.44874794, 0.48925763, 0.18490286, 0.52141644,
        0.40644877, 0.65627093, 0.20093632, 0.45528295, 0.87649485],
       [0.80819027, 0.71816238, 0.81717749, 0.19441285, 0.14116619,
        0.08752085, 0.22634285, 0.27396265, 0.49661587, 0.25177902],
       [0.70228333, 0.99954737, 0.39559573, 0.93545756, 0.69774209,
        0.5637411 , 0.46242186, 0.02560195, 0.96414085, 0.53207253],
       [0.0861727 , 0.63043437, 0.62750984, 0.09022177, 0.76198898,
        0.09459349, 0.59426197, 0.76361343, 0.81085196, 0.81815966],
       [0.19669002, 0.51963977, 0.26896092, 0.16493689, 0.60490214,
        0.57367947, 0.19004392, 0.93058552, 0.45345264, 0.40775116],
       [0.23908056, 0.19555636, 0.71618939, 0.26055683, 0.20161696,
        0.67855622, 0.18545975, 0.86780247, 0.7948997 , 0.81426512],
       [0.52611295, 0.67953444, 0.6614043

In [16]:
x.min()

0.025601945231422785

In [17]:
x.max()

0.9995473670753275

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [18]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0

In [19]:
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**34. How to get all the dates corresponding to the month of July 2016**

In [20]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

**72. How to swap two rows of an array?** 

In [ ]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])

# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sol6 = 0
# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5