In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
z = (a-np.mean(a))/np.std(a)

In [4]:
z

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [5]:
np.std(z)

0.9999999999999999

In [6]:
np.mean(z)

0.0

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
a

array([1, 2, 3, 4, 5])

In [10]:
scaler = StandardScaler()

In [ ]:
scaler.fit(a)

In [12]:
a = a.reshape(-1,1)

In [13]:
a.shape

(5, 1)

In [18]:
b = np.array([1,2,3,4,5,6,455,6,66,78,98,8,8])

In [19]:
b.shape

(13,)

In [20]:
b.reshape(-1,1).shape

(13, 1)

In [21]:
scaler.fit(a)

StandardScaler()

In [22]:
scaler.mean_

array([3.])

In [23]:
a # 3 is the mean of a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [25]:
dir(scaler)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_feature_names',
 '_check_n_features',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_reset',
 '_validate_data',
 'copy',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_params',
 'inverse_transform',
 'mean_',
 'n_features_in_',
 'n_samples_seen_',
 'partial_fit',
 'scale_',
 'set_params',
 'transform',
 'var_',
 'with_mean',
 'with_std']

In [27]:
scaler.var_

array([2.])

In [28]:
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
scaler.transform(a) #This is equal to z = (a-np.mean(a))/np.std(a)

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [32]:
scaler.inverse_transform(scaler.fit_transform(a)) # Inverse of scaler.transform(a) and equal to a

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])